# Generated by Django 3.2 on 2021-04-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210424_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.SmallIntegerField(default=18, verbose_name='возраст'),
        ),
    ]
